#! /bin/bash

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

if test -x /usr/bin/printf; then
	ECHO=/usr/bin/printf
else
	ECHO=echo
fi

wget "prodmerge.naehas.com:6060/master/services/action/server" -O /tmp/check_http_prodmaster_server.txt
master_fault_count=`grep -f /usr/lib/nagios/plugins/check_http_prodmerge_server_fault_pattern.txt -o /tmp/check_http_prodmaster_server.txt | wc -l`
master_working_count=`grep -f /usr/lib/nagios/plugins/check_http_prodmerge_server_working_pattern.txt -o /tmp/check_http_prodmaster_server.txt | wc -l`
#merge_status=`/usr/lib/nagios/plugins/check_http -I prodmerge.naehas.com -u /master/services/action/server -p 8080 -t 30 -r "UNAVAILABLE|TIMED_OUT|LOCKED|ATTENTION_REQUIRED|UNSTABLE" --invert-regex | awk '{print $2}'`

echo MASTERFAULTCOUNT: $master_fault_count
echo MASTERWORKINGCOUNT: $master_working_count

if [ $master_fault_count -gt 3 ]; then
	master_status=CRITICAL
else
	master_status=OK
fi

echo MASTERSTATUS: $master_status

if [ "$master_status" = "CRITICAL" ]; then
	exit $STATE_CRITICAL
fi

if [ $master_working_count -lt 2 ]; then
	master_status=CRITICAL
else
	master_status=OK
fi

echo MASTERSTATUS: $master_status

if [ "$master_status" = "CRITICAL" ]; then
	exit $STATE_CRITICAL
else
	exit $STATE_OK
fi
