#! /bin/bash

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

if test -x /usr/bin/printf; then
        ECHO=/usr/bin/printf
else
        ECHO=echo
fi

if [ -f /home/naehas/mtr_share/80percentused2.txt ]; then
        eightypercentused_status=`echo CRITICAL`
else
        eightypercentused_status=`echo OK`
fi

echo EIGHTYPERCENTUSEDSTATUS: $eightypercentused_status

if [ "$eightypercentused_status" = "CRITICAL" ]; then
        exit $STATE_CRITICAL
else
        exit $STATE_OK
fi
