#! /bin/bash

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

if test -x /usr/bin/printf; then
        ECHO=/usr/bin/printf
else
        ECHO=echo
fi

if [ -f /home/naehas/mtr_share/10kused2.txt ]; then
        tenkused_status=`echo CRITICAL`
else
        tenkused_status=`echo OK`
fi

echo TENKUSEDSTATUS: $tenkused_status

if [ "$tenkused_status" = "CRITICAL" ]; then
        exit $STATE_CRITICAL
else
        exit $STATE_OK
fi
