echo "parse SCIM filter examples"
./parseTree.sh "meta.lastModified gt \"2011-05-13T04:42:34Z\""
./parseTree.sh "userName eq \"bjensen\""
./parseTree.sh "name.familyName co \"O'Malley\""
./parseTree.sh "userName sw \"J\""
./parseTree.sh "title pr"
./parseTree.sh "meta.lastModified gt \"2011-05-13T04:42:34Z\""
./parseTree.sh "meta.lastModified ge \"2011-05-13T04:42:34Z\""
./parseTree.sh "meta.lastModified lt \"2011-05-13T04:42:34Z\""
./parseTree.sh "meta.lastModified le \"2011-05-13T04:42:34Z\""
./parseTree.sh "title pr and userType eq \"Employee\""
./parseTree.sh "title pr or userType eq \"Intern\""
./parseTree.sh "userType eq \"Employee\" and (emails co \"example.com\" or emails co \"example.org\")"
