
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-AGaramond-Bold.pfm BOA-AGaramond-Bold.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-AGaramond-BoldItalic.pfm BOA-AGaramond-BoldItalic.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-AGaramond-Italic.pfm BOA-AGaramond-Italic.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-AGaramond-Regular.pfm BOA-AGaramond-Regular.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-AGaramond-Semibold.pfm BOA-AGaramond-Semibold.xml

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-AGaramond-SemiboldItali.pfm BOA-AGaramond-SemiboldItali.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Arial-Black.pfm BOA-Arial-Black.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-ArialMT.pfm BOA-ArialMT.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Helvetica-Bold.pfm BOA-Helvetica-Bold.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Helvetica-Condensed-Bo1.pfm BOA-Helvetica-Condensed-Bo1.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Helvetica-Condensed-Bol.pfm BOA-Helvetica-Condensed-Bol.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Helvetica-Condensed-Obl.pfm BOA-Helvetica-Condensed-Obl.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Helvetica-Condensed.pfm BOA-Helvetica-Condensed.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Helvetica.pfm BOA-Helvetica.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-HelveticaNeue-ThinCondO.pfm BOA-HelveticaNeue-ThinCondO.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-StoneSans-Semibold.pfm BOA-StoneSans-Semibold.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-StoneSans-SemiboldItali.pfm BOA-StoneSans-SemiboldItali.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-Black.pfm BOA-Univers-Black.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-BlackOblique.pfm BOA-Univers-BlackOblique.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-Bold.pfm BOA-Univers-Bold.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-BoldOblique.pfm BOA-Univers-BoldOblique.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-Condensed.pfm BOA-Univers-Condensed.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-CondensedObliqu.pfm BOA-Univers-CondensedObliqu.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-Light.pfm BOA-Univers-Light.xml

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-LightOblique.pfm BOA-Univers-LightOblique.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers-Oblique.pfm BOA-Univers-Oblique.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Univers.pfm BOA-Univers.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Verdana-Bold.pfm BOA-Verdana-Bold.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Verdana-BoldItalic.pfm BOA-Verdana-BoldItalic.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Verdana-Italic.pfm BOA-Verdana-Italic.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/BOA-Verdana.pfm BOA-Verdana.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/FranklinGothic-Book.pfm FranklinGothic-Book.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/FranklinGothic-BookItal.pfm FranklinGothic-BookItal.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/FranklinGothic-Demi.pfm FranklinGothic-Demi.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/FranklinGothic-DemiItal.pfm FranklinGothic-DemiItal.xml 
 
java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/FranklinGothic-Heavy.pfm FranklinGothic-Heavy.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/FranklinGothic-HeavyItal.pfm FranklinGothic-HeavyItal.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/ZapfDingbats.pfm ZapfDingbats.xml




java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/AkzidenzGroteskBE-Bold.pfm AkzidenzGroteskBE-Bold.xml 

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/AkzidenzGroteskBE-BoldIt.pfm AkzidenzGroteskBE-BoldIt.xml

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/AkzidenzGroteskBE-It.pfm AkzidenzGroteskBE-It.xml

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/AkzidenzGroteskBE-Md.pfm AkzidenzGroteskBE-Md.xml

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/AkzidenzGroteskBE-MdIt.pfm AkzidenzGroteskBE-MdIt.xml

java -cp /Users/robertg/Downloads/fop-0.95/build/fop.jar:/Users/robertg/Downloads/fop-0.95/lib/serializer-2.7.0.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-logging-1.0.4.jar:/Users/robertg/Downloads/fop-0.95/lib/commons-io-1.3.1.jar:/Users/robertg/Downloads/fop-0.95/lib/xmlgraphics-commons-1.3.1.jar org.apache.fop.fonts.apps.PFMReader /Users/robertg/Desktop/type1/AkzidenzGroteskBE-Regular.pfm AkzidenzGroteskBE-Regular.xml
