#!/bin/bash

PROGRAM_NAME=`basename $0`

usage() {
    echo "ERROR: usage"
    echo "usage: ${PROGRAM_NAME} <source> <type> <path> <suffix>"
    echo ""
    exit 1;
}

if [[ (-z $1) || (-z $2) || (-z $3) || (-z $4) ]]; then
    usage
fi

scriptDir=`dirname $0`;

eval `ssh-agent -s`
echo "SSH_AGENT_PID = $SSH_AGENT_PID"
ssh-add

killAgentAndExit() {
    kill -9 $SSH_AGENT_PID
    exit $1
}

if [[ "base-dashboard" == "$1" ]]; then
    echo "ERROR: Retiring a base-dashboard instance not available.";
    killAgentAndExit 1;
elif [[ "base-ilp" == "$1" ]]; then
    ${scriptDir}/retire-base-ilp $2 $3 $4
else
    echo "ERROR: $1 not supported.";
    killAgentAndExit 1;
fi

if [[ $? -ne 0 ]]; then
    echo "ERROR: retire failed."
    killAgentAndExit 1
fi

killAgentAndExit 0
