#!/usr/bin/perl -w

$PROGRAM_NAME=`basename $0`;
chomp($PROGRAM_NAME);

if ($#ARGV < 0) {
	print("usage: $PROGRAM_NAME <path_to_svn_checkout>\n");
	exit 1;
}

$pathToSvn=$ARGV[0];

if (! -d "$pathToSvn") {
	print("ERROR: ${pathToSvn} does not exist.\n");
	exit 1;
}

@svnStatus=`svn status "$pathToSvn" | grep "^\!"`;
foreach $LINE  (@svnStatus) {
	chomp($LINE);
	$LINE =~ s#^.\s+##g;
	print("svn revert \"${LINE}\"\n");
	`svn revert "${LINE}"`;
}
