#!/bin/bash

PROGRAM_NAME=`basename $0`
WORKING_DIR=`dirname $0`

usage() {
    echo "ERROR: usage"
    echo "${PROGRAM_NAME} <old_repository_url> <new_repository_url> <list_location> "
    echo "      old_repos...    eg: svn+ssh://dev1.naehas.com/home/svn/repository"
    echo "      new_repos...    eg: svn+ssh://svn.naehas.com/home/svn/repository"
    echo "      list_location   eg: /home/naehas/blar.txt; optional. If not present, will generate list"
    echo ""
    exit 1;
}

if [[ (-z $1) || (-z $2) || (-z $3) ]]; then
    usage
fi

oldRep=$1
newRep=$2
listLocation=$3

main() {
    if [[ ! -f $listLocation ]]; then
        echo "ERROR: $listLocation is not a file."
        exit 1;
    fi

    eval `ssh-agent -s`
    if [[ $? -ne 0 ]]; then
        echo "evalling ssh-agent -s failed"
        exit 1;
    fi
    ssh-add
    if [[ $? -ne 0 ]]; then
        echo "ssh-add failed"
        kill -9 $SSH_AGENT_PID
        exit 1;
    fi

    for instanceDir in $(cat $listLocation)
    do
        if [[ ! -d $instanceDir ]]; then
            echo "WARN: $instanceDir not a directory"
        else
            svn switch --relocate $oldRep $newRep $instanceDir
            if [[ $? -ne 0 ]]; then
                echo "WARN: $instanceDir could not switch"
            fi
        fi
    done

    echo "Killing ssh-agent $SSH_AGENT_PID"
    kill -9 $SSH_AGENT_PID

    exit 0;
}

main
